package hu.gov.allamkincstar.deviza;

import java.awt.event.KeyEvent;
import java.io.IOException;
import java.net.URL;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.DocumentListener;
import javax.xml.XMLConstants;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;
import org.xml.sax.SAXException;

/**
 *
 * @author Soltesz Edit
 * Deviza atvalto
 */
public class DevizaAtvalto extends javax.swing.JFrame {

    private HashMap<String, Float> devizaMap = new HashMap<>();
    private float forintArfolyam;
    private Document doc;
    private String kivalasztottDevizanem;
    private float kivalasztottDevizaArfolyam;

    /**
     * Creates new form DevizaAtvalto
     */
    public DevizaAtvalto() {
        initComponents();
        feltoltButton.setEnabled(true);
        devizanemComboBox.setEnabled(false);
        atvaltButton.setEnabled(false);
        atvaltandoTextField.setEnabled(false);
        atvaltottTextField.setEnabled(false);
        uzenetDialog.setVisible(false);

        atvaltandoTextField.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                atvaltottTextField.setText("");
            }
            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                atvaltottTextField.setText("");
            }
            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                atvaltottTextField.setText("");
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        uzenetDialog = new javax.swing.JDialog();
        uzenetLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        udvzloLabel = new javax.swing.JLabel();
        forrasLabel = new javax.swing.JLabel();
        devizanemComboBox = new javax.swing.JComboBox<>();
        feltoltButton = new javax.swing.JButton();
        atvaltandoLabel = new javax.swing.JLabel();
        atvaltandoTextField = new javax.swing.JTextField();
        atvaltButton = new javax.swing.JToggleButton();
        atvaltottLabel = new javax.swing.JLabel();
        atvaltottTextField = new javax.swing.JTextField();

        uzenetDialog.setTitle("Figyelem!");
        uzenetDialog.setPreferredSize(new java.awt.Dimension(1500, 1500));
        uzenetDialog.setSize(new java.awt.Dimension(250, 250));

        uzenetLabel.setText("Sikertelen feltöltés!");
        uzenetLabel.setToolTipText("");

        javax.swing.GroupLayout uzenetDialogLayout = new javax.swing.GroupLayout(uzenetDialog.getContentPane());
        uzenetDialog.getContentPane().setLayout(uzenetDialogLayout);
        uzenetDialogLayout.setHorizontalGroup(
            uzenetDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(uzenetDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(uzenetDialogLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(uzenetLabel)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        uzenetDialogLayout.setVerticalGroup(
            uzenetDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(uzenetDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(uzenetDialogLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(uzenetLabel)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        uzenetDialog.getAccessibleContext().setAccessibleParent(jPanel1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Deviza átváltása forintba");
        setBackground(new java.awt.Color(153, 153, 0));

        jPanel1.setBackground(new java.awt.Color(166, 210, 210));

        udvzloLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        udvzloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        udvzloLabel.setText("Euro deviza referenciaárfolyamok alapján a megadott összeg átváltása forintba a kiválasztott valutanemről.");

        forrasLabel.setText("Forrás: https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/index.en.html");

        devizanemComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                devizanemComboBoxActionPerformed(evt);
            }
        });

        feltoltButton.setText("Aktuális euro deviza referenciaárfolyamok feltöltése");
        feltoltButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feltoltButtonActionPerformed(evt);
            }
        });

        atvaltandoLabel.setText("Átváltandó összeg:");

        atvaltandoTextField.setEditable(false);
        atvaltandoTextField.setBackground(new java.awt.Color(240, 240, 240));
        atvaltandoTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                atvaltandoTextFieldKeyTyped(evt);
            }
        });

        atvaltButton.setText("Átváltás");
        atvaltButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atvaltButtonActionPerformed(evt);
            }
        });

        atvaltottLabel.setText("Átváltott összeg (HUF):");

        atvaltottTextField.setEditable(false);
        atvaltottTextField.setBackground(new java.awt.Color(240, 240, 240));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(forrasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(udvzloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 858, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(devizanemComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(feltoltButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(atvaltottLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(atvaltButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(atvaltandoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(atvaltandoTextField)
                                    .addComponent(atvaltottTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))))))
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(udvzloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(feltoltButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(devizanemComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atvaltandoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atvaltandoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(atvaltButton)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(atvaltottTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atvaltottLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                .addComponent(forrasLabel)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * arfolyamokat tartalmazo xml letoltese: https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml
     * @return true, ha sikeres, false, ha nem sikerult a letoltes
     */
    public boolean xmlOpen() {
        try {
            new CertificatValidator();
            final URL url = new URL("https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml");
            
            DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
            dbf.setFeature(XMLConstants.FEATURE_SECURE_PROCESSING, true);
            DocumentBuilder db = dbf.newDocumentBuilder();
            doc = db.parse(url.openStream());
            doc.getDocumentElement().normalize();

            return true;
        } catch (ParserConfigurationException | IOException | SAXException ex) {
            Logger.getLogger(DevizaAtvalto.class.getName()).log(Level.SEVERE, null, ex);
            return false;
        } catch (Exception ex1) {
            Logger.getLogger(DevizaAtvalto.class.getName()).log(Level.SEVERE, null, ex1);
            return false;
        }
    }

    /**
     * erteklistabol kivalasztott elemebol a devizanem, arfolyam meghatarozasa 
     */
    public void kivalasztottDevizaMeghataroz() {
        kivalasztottDevizaArfolyam = 0.0f;
        kivalasztottDevizanem = null;
        if (devizanemComboBox.getItemCount() != 0) {
            kivalasztottDevizanem = devizanemComboBox.getSelectedItem().toString().substring(0, devizanemComboBox.getSelectedItem().toString().indexOf(" árfolyam: "));
            kivalasztottDevizaArfolyam = devizaMap.get(kivalasztottDevizanem).floatValue();
            atvaltandoLabel.setText("Átváltandó összeg " + "(" + kivalasztottDevizanem + "):");
        }
    }

    /**
     * Erteklista feltoltese devizanemekkel
     * @param docu
     * @return true, ha sikeres, false, ha nem sikerult az erteklista feltoltese
     */
    public boolean erteklistaFeltolt(Document docu) {
        try {
            NodeList cubeNodeList = docu.getElementsByTagName("Cube");

            for (int i = 0; i < cubeNodeList.getLength(); i++) {
                Element cubeElement = (Element) cubeNodeList.item(i);

                if (cubeElement.getAttribute("currency") != null && !cubeElement.getAttribute("currency").isEmpty()) {
                    devizaMap.put(cubeElement.getAttribute("currency"), Float.valueOf(cubeElement.getAttribute("rate")));
                    devizanemComboBox.addItem(cubeElement.getAttribute("currency") + " árfolyam: " + cubeElement.getAttribute("rate"));
                    if (cubeElement.getAttribute("currency").equals("HUF")) {
                        forintArfolyam = Float.valueOf(cubeElement.getAttribute("rate")).floatValue();
                    }
                }
            }
            kivalasztottDevizaMeghataroz();
            return true;
        } catch (Exception ex) {
            Logger.getLogger(DevizaAtvalto.class.getName()).log(Level.SEVERE, null, ex);
            return false;
        }
    }

    /**
     * uploads the Currency list
     */
    private void feltoltButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feltoltButtonActionPerformed

        devizanemComboBox.setEnabled(true);
        devizanemComboBox.removeAllItems();
        Boolean eredmeny = xmlOpen() ? (erteklistaFeltolt(doc) ? Boolean.TRUE : Boolean.FALSE) : Boolean.FALSE;
        if (!(eredmeny)) {
            devizanemComboBox.setEnabled(false);
            uzenetLabel.setText("Sikertelen feltöltés!");
            uzenetDialog.setVisible(true);
            atvaltButton.setEnabled(false);
            atvaltottTextField.setEnabled(false);
        } else {
            atvaltButton.setEnabled(true);
            atvaltandoTextField.setEnabled(true);
            atvaltandoTextField.setEditable(true);
        }
    }//GEN-LAST:event_feltoltButtonActionPerformed

    /**
     * atvaltas gomb megnyomasara elvegzi az atvaltast
     * @param evt 
     */
    private void atvaltButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atvaltButtonActionPerformed

        try {
            if (atvaltandoTextField.getText() != null && !atvaltandoTextField.getText().isEmpty()) {
                float atvaltott = (Float.valueOf(atvaltandoTextField.getText()).floatValue() / kivalasztottDevizaArfolyam) * forintArfolyam;
                float kerekitett  = Math.round(atvaltott / 5) * 5f;
                atvaltottTextField.setText(String.valueOf((int)kerekitett));
            } else {
                uzenetLabel.setText("Adja meg az átváltandó összeget!");
                uzenetDialog.setVisible(true);
            }
        } catch (NumberFormatException ex) {
            Logger.getLogger(DevizaAtvalto.class.getName()).log(Level.SEVERE, null, ex);
            uzenetLabel.setText("Érvénytelen összeg!");
            uzenetDialog.setVisible(true);
        }
    }//GEN-LAST:event_atvaltButtonActionPerformed

    /**
     * erteklistabol valasztas eseten hajtodik vegre
     * @param evt 
     */
    private void devizanemComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devizanemComboBoxActionPerformed
        kivalasztottDevizaMeghataroz();
        atvaltottTextField.setText("");
    }//GEN-LAST:event_devizanemComboBoxActionPerformed

    /**
     * atvaltando osszeg megadasakor hajtodik vegre, csak szamot lehet megadni
     * @param evt 
     */
    private void atvaltandoTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_atvaltandoTextFieldKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE ) {
            evt.consume();
        }
    }//GEN-LAST:event_atvaltandoTextFieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DevizaAtvalto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DevizaAtvalto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DevizaAtvalto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DevizaAtvalto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DevizaAtvalto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton atvaltButton;
    private javax.swing.JLabel atvaltandoLabel;
    private javax.swing.JTextField atvaltandoTextField;
    private javax.swing.JLabel atvaltottLabel;
    private javax.swing.JTextField atvaltottTextField;
    private javax.swing.JComboBox<String> devizanemComboBox;
    private javax.swing.JButton feltoltButton;
    private javax.swing.JLabel forrasLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel udvzloLabel;
    private javax.swing.JDialog uzenetDialog;
    private javax.swing.JLabel uzenetLabel;
    // End of variables declaration//GEN-END:variables
}
